[workspace]
members = ["shared"]
build-members = []
test-members = []
compile-option = "-Woff unused"
override-compile-option = ""
link-option = ""
target-dir = ""
script-dir = ""

[profile]
experimental = true

[dependencies]

[target.aarch64-apple-ios-simulator.debug.bin-dependencies]
path-option = ["target/aarch64-apple-ios-simulator/debug/objc"]

[target.aarch64-apple-ios-simulator.release.bin-dependencies]
path-option = ["target/aarch64-apple-ios-simulator/release/objc"]

[target.aarch64-apple-darwin.debug.bin-dependencies]
path-option = ["target/aarch64-apple-darwin/debug/objc"]

[target.aarch64-apple-darwin.release.bin-dependencies]
path-option = ["target/aarch64-apple-darwin/release/objc"]
