#!/usr/bin/env bash
set -euo pipefail

source ./scripts/utils.sh

# $1 - headers directory
write_umbrella_header() {
    local umbrella="$1/$KIT_NAME.h"
    local -a headers=()
    local header
    for header in "$1"/*.h; do
        [ "$header" = "$umbrella" ] || headers+=("${header##*/}")
    done

    {
        printf '// Generated by scripts/post-build.sh. Do not edit.\n'
        printf '#import "%s"\n' "${headers[@]}"
    } > "$umbrella"
}

# $1 - target triple
# $2 - profile
# $3 - directory for the object files
compile_objc_glue() {
    local sdk_name
    sdk_name="$(sdk_for "$1")"
    local sdk
    sdk="$(xcrun --sdk "$sdk_name" --show-sdk-path)"
    local clang_target_triple
    clang_target_triple="$(clang_target_triple_for "$1")"

    local -a optimization
    case "$2" in
        debug) optimization=(-O0 -g) ;;
        *)     optimization=(-O2) ;;
    esac

    local source object
    for source in "$OBJC_GEN_DIR"/*.m; do
        object="$3/${source##*/}"
        object="${object%.m}.o"
        xcrun --sdk "$sdk_name" clang -c "$source" -o "$object" \
            -target "$clang_target_triple" -isysroot "$sdk" \
            -fobjc-arc -Wall "${optimization[@]}" \
            -I "$OBJC_GEN_DIR" -I "$OBJC_SUPPORT_DIR"
    done
}

# $1 - target triple
# $2 - profile
build_kit_slice() {
    local output_dir
    output_dir="$(cjpm_output_dir_for "$1" "$2")"
    local slice_dir="$output_dir/$KIT_NAME"

    rm -rf "$slice_dir"
    mkdir -p "$slice_dir/Headers" "$slice_dir/obj"

    compile_objc_glue "$1" "$2" "$slice_dir/obj"

    local -a members=("$output_dir/tsn"/*.a "$slice_dir/obj"/*.o)
    if [ "$BUNDLE_RUNTIME" = 1 ]; then
        # cjinterop.o carries initCJRuntime, which the generated +initialize
        # calls; cjstart.o and section.o are what a static Cangjie image starts from.
        local cangjie_lib_dir
        cangjie_lib_dir="$(cangjie_lib_dir_for "$1")"
        local archive
        for archive in "$cangjie_lib_dir"/*.a; do
            # compiler-rt belongs to whoever links the application, and the macOS
            # copies hold macCatalyst objects next to the macOS ones, which a
            # single xcframework slice is not allowed to mix
            case "${archive##*/}" in
                libclang_rt*) continue ;;
            esac
            members+=("$archive")
        done
        members+=("$cangjie_lib_dir/section.o"
                  "$cangjie_lib_dir/cjstart.o"
                  "$cangjie_lib_dir/cjinterop.o")
    fi
    # Some of the runtime archives are fat; -arch_only keeps the artifact honest
    # about the one architecture the Cangjie side was built for.
    xcrun libtool -static -no_warning_for_no_symbols -arch_only "$(arch_for "$1")" \
        -o "$slice_dir/lib$KIT_NAME.a" "${members[@]}"
    rm -rf "$slice_dir/obj"

    cp "$OBJC_GEN_DIR"/*.h "$OBJC_SUPPORT_DIR"/*.h "$slice_dir/Headers/"
    cp "$OBJC_SUPPORT_DIR/module.modulemap" "$slice_dir/Headers/"
    write_umbrella_header "$slice_dir/Headers"
}

# The Xcode project names one fixed path and cannot choose between the profiles,
# so what the app links is whichever profile was packaged last. Building the kit
# for the profile the app is about to be built against is therefore part of the
# app's build, not something the project can decide for itself.
# $1 - the xcframework to publish
publish_kit() {
    mkdir -p "$APPLE_KIT_DIR"
    rm -rf "$APPLE_KIT_DIR/$KIT_NAME.xcframework"
    cp -R "$1" "$APPLE_KIT_DIR/"
}

# An xcframework carries the slices of every triple at once, so it is rebuilt
# from whatever slices the profile has and the same copy is dropped next to each
# of them — Xcode can be pointed at any of those directories.
# $1 - profile
create_xc_framework() {
    local -a slices=()
    local target slice
    for target in "${SUPPORTED_TARGETS[@]}"; do
        slice="$(cjpm_output_dir_for "$target" "$1")/$KIT_NAME"
        if [ ! -d "$slice" ]; then
            continue
        fi
        # Only this build's target was just compiled; the rest are whatever an
        # earlier build left behind. One that predates the current sources would
        # ship objects built from code that has since changed, so it is dropped
        # rather than packed under a fresh name. The note below reaches only
        # cjpm's script-log, so the signal that carries is the xcframework
        # itself: it holds the slices that are current and no others.
        if kit_slice_is_current "$slice/lib$KIT_NAME.a"; then
            slices+=("$slice")
        else
            printf '%s: %s slice is older than the sources, leaving it out; build that target to include it\n' \
                "$KIT_NAME" "$target" >&2
        fi
    done
    [ "${#slices[@]}" -gt 0 ] || return 0

    local -a args=()
    for slice in "${slices[@]}"; do
        args+=(-library "$slice/lib$KIT_NAME.a" -headers "$slice/Headers")
    done

    local staging
    staging="$(mktemp -d)"
    xcrun xcodebuild -create-xcframework "${args[@]}" \
        -output "$staging/$KIT_NAME.xcframework" > /dev/null

    for slice in "${slices[@]}"; do
        rm -rf "${slice%/*}/$KIT_NAME.xcframework"
        cp -R "$staging/$KIT_NAME.xcframework" "${slice%/*}/"
    done
    publish_kit "$staging/$KIT_NAME.xcframework"
    rm -rf "$staging"
}

# $1 - target triple
# $2 - profile
package_xc_framework_for_profile() {
    local output_dir
    output_dir="$(cjpm_output_dir_for "$1" "$2")"

    # Skipping the profile this run did not build matters: the glue on disk
    # belongs to this compilation, and pairing it with the other profile's older
    # archive builds a slice whose halves disagree — something libtool cannot
    # see and only an application link would ever catch.
    [ -d "$output_dir/tsn" ] || return 0
    built_in_this_run "$output_dir/tsn" || return 0

    build_kit_slice "$1" "$2"
    create_xc_framework "$2"
}

package_xc_framework() {
    local profile
    for profile in "${BUILD_PROFILES[@]}"; do
        package_xc_framework_for_profile "$1" "$profile"
    done
}

package_platform_artifact() {
    local target_interop_lang
    target_interop_lang="$(target_interop_lang_for "$1")"
    case "$target_interop_lang" in
        objc) package_xc_framework "$1" ;;
        *) return 1 ;;
    esac
}

main() {
    package_platform_artifact "$1"
}

main "$@"
