#!/usr/bin/env bash

set -euo pipefail

source ./scripts/utils.sh

# $1 - target triple
# $2 - profile
copy_objc_libs_for_profile() {
    local cangjie_modules_dir
    cangjie_modules_dir="$(cangjie_modules_dir_for "$1")"
    local target_dir
    target_dir="$MODULE_ROOT/target/$1/$2/objc"

    # The directory has to exist whichever target is being built
    mkdir -p "$target_dir"
    cp "$cangjie_modules_dir"/objc.* "$target_dir/"
}

copy_objc_libs() {
    local profile
    for profile in "${BUILD_PROFILES[@]}"; do
        copy_objc_libs_for_profile "$1" "$profile"
    done
}

copy_libs_for_target() {
    local target_interop_lang
    target_interop_lang="$(target_interop_lang_for "$1")"
    case "$target_interop_lang" in
        objc) copy_objc_libs "$1" ;;
        *) return 1 ;;
    esac
}

copy_libs() {
    local target
    for target in "${SUPPORTED_TARGETS[@]}"; do
        copy_libs_for_target "$target"
    done
}

# $1 - os
# $2 - mirrors output dir
# $3 - generator config path
generate_objc_mirrors_for_os() {
    local target
    target="$(objc_mirror_target_for "$1")"
    local sdk_name
    sdk_name="$(sdk_for "$target")"
    local sdk
    sdk="$(xcrun --sdk "$sdk_name" --show-sdk-path)"
    local res_dir
    res_dir="$(xcrun --sdk "$sdk_name" clang -print-resource-dir)"

    mkdir -p "$2"
    sed -e "s|@SDK@|$sdk|g" -e "s|@RES_DIR@|$res_dir|g" \
        -e "s|@CLANG_TRIPLE@|$(clang_target_triple_for "$target")|g" \
        -e "s|@EXTRA_ARGS@|$(objc_extra_clang_args_for "$target")|g" \
        -e "s|@PACKAGE@|$OBJC_MIRRORS_PACKAGE.$(objc_mirror_package_for "$1")|g" \
        -e "s|@INCLUDE@|$(objc_mirror_include_list)|g" \
        -e "s|@OUTPUT_PATH@|$2|g" \
        "$MODULE_ROOT/ObjCInteropGen.toml.in" > "$3"

    local rc=0
    ObjCInteropGen "$3" 2>&1 | grep -vE "unsupported feature" || rc="${PIPESTATUS[0]}"
    return "$rc"
}

# $1 - directory holding the mirror subpackages
write_objc_mirror_facade() {
    {
        printf '// Generated by scripts/pre-build.sh. Do not edit.\n'
        printf 'package %s\n' "$OBJC_MIRRORS_PACKAGE"

        local mirror_os
        for mirror_os in "${OBJC_MIRROR_OS[@]}"; do
            printf '\n@When[os == "%s"]\npublic import %s.%s.*\n' \
                "$mirror_os" "$OBJC_MIRRORS_PACKAGE" \
                "$(objc_mirror_package_for "$mirror_os")"
        done
    } > "$1/foundation.cj"
}

generate_objc_mirrors() {
    local staging
    staging="$(mktemp -d)"
    local tree="$staging/foundation"

    local mirror_os package
    for mirror_os in "${OBJC_MIRROR_OS[@]}"; do
        package="$(objc_mirror_package_for "$mirror_os")"
        if ! generate_objc_mirrors_for_os \
                "$mirror_os" "$tree/$package" "$staging/$package.toml"; then
            rm -rf "$staging"
            die "ObjCInteropGen failed for $mirror_os"
        fi
    done
    write_objc_mirror_facade "$tree"

    mkdir -p "$OBJC_MIRRORS_DIR"
    rsync -rc --delete "$tree/" "$OBJC_MIRRORS_DIR/"
    rm -rf "$staging"
}

generate_mirrors() {
    local target_interop_lang
    target_interop_lang="$(target_interop_lang_for "$1")"
    case "$target_interop_lang" in
        objc) generate_objc_mirrors ;;
        *) return 1 ;;
    esac
}

# On a cross build cjpm puts the host target's packages first on cjc's import
# path, ahead of the directory for the target actually being built:
#
#     --import-path=.../target/release                       <- host
#     --import-path=.../target/<triple>/release
#
# cjc takes the first .cjo it finds, so a macOS build left lying around lends its
# interfaces to the next iOS build.
#
# $1 - target triple
drop_host_package_output() {
    if is_host_target "$1"; then
        return 0
    fi

    local profile
    for profile in "${BUILD_PROFILES[@]}"; do
        rm -rf "$MODULE_ROOT/target/$profile/tsn"
    done
}

main() {
    mark_build_started
    drop_host_package_output "$1"
    copy_libs
    generate_mirrors "$@"
}

main "$@"
