[package]
cjc-version = "1.3.0"
name = "tsn"
organization = ""
description = "nothing here"
version = "1.0.0"
target-dir = ""
script-dir = ""
output-type = "static"
compile-option = ""
override-compile-option = ""
link-option = ""

[package.package-configuration."tsn.objc.usecase"]
compile-option = "--objc-interop-output-dir=shared/native/objc/generated"

[dependencies]
